### ISSUE TITLE
How to add new speaker for enrollment?

### ISSUE THREAD

**Issue by Sadam1195** [jymsuper/SpeakerRecognition_tutorial#1]
What modifications do I need to do in order to add new speaker using `enroll.py` file. @jymsuper

**Comment by jymsuper** [comment]
In 'split_enroll_and_test' function, we get a list of both enroll and test files.
It is denoted as 'DB_all' and it is a pandas dataframe.
According to the filename, we split the list and get lists of enroll and test files, which are 'enroll_DB' and 'test_DB' respectively.

In 'feat_logfbank_nfilt40/test', I put both enroll and test files for each speaker.
In each speaker folder (e.g., 103F3021), you can see both 'enroll.p' and 'test.p'.
When you need to add a new speaker, create a new speaker folder and add 'enroll.p' file in the folder.

**Comment by Sadam1195** [comment]
Thanks for clearing that up.
