### ISSUE TITLE
enroll_per_spk does not average

### ISSUE THREAD

**Issue by cirograciapons** [jymsuper/SpeakerRecognition_tutorial#11]
https://github.com/jymsuper/SpeakerRecognition_tutorial/blob/6dce64657632660a791e25624e4257c53c7257d6/enroll.py#L73
states that outputs the averaged d-vector

however there is not averagin operation and only agregates embeddings
https://github.com/jymsuper/SpeakerRecognition_tutorial/blob/6dce64657632660a791e25624e4257c53c7257d6/enroll.py#L90

is that true?

**Comment by jymsuper** [comment]
You are right. To average d-vectors, you have to divide the summation by the number of files.
However, in this case, there is only one file. Therefore, it does not matter.
