### ISSUE TITLE
Is there any related papers for this code as a reference?

### ISSUE THREAD

**Issue by Pandade1997** [jymsuper/SpeakerRecognition_tutorial#14]

**Comment by jymsuper** [comment]
Hi. This code is for beginners containing only basic concept of speaker recognition.

You can refer my paper below.

"Spatial Pyramid Encoding with Convex Length Normalization for Text-Independent Speaker Verification"

The code does not deal with the algorithm of the above paper, but the naive model is implemented in the code (the model using global average pooling and cross entropy loss).
 
Thank you.
