### ISSUE TITLE
Can you provide how to convert wav to .p file 

### ISSUE THREAD

**Issue by Adarsh474532** [jymsuper/SpeakerRecognition_tutorial#15]
please provide a file

**Comment by jymsuper** [comment]
Hi. Please use the below code.

https://github.com/seongmin-kye/meta-SR/blob/master/feat_extract/feature_extraction.py

**Comment by Adarsh474532** [comment]
sir ,how to convert single wav to p file

**Comment by jymsuper** [comment]
Please refer the function  "extract_MFB" in the code.

**Comment by Adarsh474532** [comment]
Thank you Sir

**Comment by Adarsh474532** [comment]
Thank you so much

**Comment by Adarsh474532** [comment]
SIr i am unable to convert single wav to p file, can you do it please
