### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Adarsh474532** [jymsuper/SpeakerRecognition_tutorial#16]
SIr i am unable to convert single wav to p file, can you do it please sir

**Comment by jymsuper** [comment]
In the function 'extract_MFB' of the below code,
https://github.com/seongmin-kye/meta-SR/blob/master/feat_extract/feature_extraction.py

1) sr, audio = sio.wavfile.read(filename)
=> Read the audio file

2) features, energies = fbank(audio, samplerate=c.SAMPLE_RATE, nfilt=c.FILTER_BANK, winlen=0.025, winfunc=np.hamming)
features = 20 * np.log10(np.maximum(features,1e-5))
=> Extract features using the audio

3) features = normalize_frames(features, Scale=c.USE_SCALE)
total_features = features
=> Normalize the features

4) speaker_label = speaker_folder # set label as a folder name (recommended). Convert this to speaker index when training
    feat_and_label = {'feat':total_features, 'label':speaker_label}
with open(output_filename, 'wb') as fp:
            pickle.dump(feat_and_label, fp)
=> Save features and labels as a dictionary. The file name is 'output_filename' which ends in '.p' format.

Please follow the above instruction.
