### ISSUE TITLE
verifification.py 

### ISSUE THREAD

**Issue by Adarsh474532** [jymsuper/SpeakerRecognition_tutorial#17]
sir speaker is different but verify is correct, how sir.

![image](https://user-images.githubusercontent.com/51045580/127153743-68e4e45a-4336-4816-bf11-25d0f6a3f830.png)

**Comment by Adarsh474532** [comment]
result is wrong

**Comment by jymsuper** [comment]
The actual result is not wrong. It just shows wrong name.
It says 'Claimed speaker : test'. Here, the 'test' is the name of the feature folder.

Are you using Window OS? 
Then, please change the code as follows (I assumed that the code is working on Ubuntu OS).

In the function 'perform_verification' of 'verification.py',
Please change the code as below (use os.sep instead of '/'). 
   test_spk = test_filename.split(os.sep)[-2].split('_')[0]

**Comment by Adarsh474532** [comment]
![image](https://user-images.githubusercontent.com/51045580/127262977-34318e04-234b-449b-9c7d-086ca988d1ae.png)
![image](https://user-images.githubusercontent.com/51045580/127264504-6a6e3a04-4e93-4e69-90c8-0e2c8f9f9b2f.png)

This time is also wrong.

**Comment by Adarsh474532** [comment]
![image](https://user-images.githubusercontent.com/51045580/127265399-23729bc6-c472-4013-be6f-21360a87a0ca.png)

but test with another embedding then result is right, how

**Comment by jymsuper** [comment]
Did you change what I wrote above? In your screen, claimed speaker is 'feat'
True speaker or Claimed speaker should be the name of the speaker folder. 
Please carefully check the function 'perform_verification' and debug yourself. 
I guess this is just the print issue.

**Comment by Adarsh474532** [comment]
def perform_verification(use_cuda, model, embeddings, enroll_speaker, test_filename, test_frames, thres):
    enroll_embedding = embeddings[enroll_speaker]
    test_embedding = get_embeddings(use_cuda, test_filename, model, test_frames)

    score = F.cosine_similarity(test_embedding, enroll_embedding)
    score = score.data.cpu().numpy() 
        
    if score > thres:
        result = 'Accept'
    else:
        result = 'Reject'
        
    test_spk = test_filename.split(os.sep)[-2].split('_')[0]
    print("\n=== Speaker verification ===")
    print("True speaker: %s\nClaimed speaker : %s\n\nResult : %s\n" %(enroll_speaker, test_spk, result))
    print("Score : %0.4f\nThreshold : %0.2f\n" %(score, thres))

**Comment by Adarsh474532** [comment]
but , with old speaker work is correctly.

**Comment by jymsuper** [comment]
The folder structure should be the same. Check the folder structure.
Also, check the variable 'test_spk' and 'test_filename'.

**Comment by Adarsh474532** [comment]
![image](https://user-images.githubusercontent.com/51045580/127268489-6c1a6d15-70cf-4dcd-bbdd-7e68e7d621c6.png)
![image](https://user-images.githubusercontent.com/51045580/127268511-7f83d7e0-f17a-44e8-be90-c5af771932a9.png)
 my structure

**Comment by Adarsh474532** [comment]
[speaker verification.docx](https://github.com/jymsuper/SpeakerRecognition_tutorial/files/6890530/speaker.verification.docx)


Check the code please

**Comment by jymsuper** [comment]
I don't know why 'feat' is printed for 'Claimed speaker'.
Check the variable 'test_spk' and 'test_filename'.

**Comment by Adarsh474532** [comment]
> [speaker verification.docx](https://github.com/jymsuper/SpeakerRecognition_tutorial/files/6890530/speaker.verification.docx)
> 
> Check the code please

code is correct or wrong

**Comment by jymsuper** [comment]
I think the instruction is enough. Please debug yourself. 
This is just basic python debugging, not related to speaker verification algorithm.
As I already mentioned, I guess this is just the print issue. 
Please check the variable 'test_spk' and 'test_filename'.

**Comment by Adarsh474532** [comment]
![image](https://user-images.githubusercontent.com/51045580/127272438-d89bf41c-249a-4458-9c01-c96442b1cb1f.png)


error in sr_dataset.py

**Comment by Adarsh474532** [comment]
> I think the instruction is enough. Please debug yourself.
> This is just basic python debugging, not related to speaker verification algorithm.
> As I already mentioned, I guess this is just the print issue.
> Please check the variable 'test_spk' and 'test_filename'.

ok sir

**Comment by jymsuper** [comment]
You can ignore the main function in 'SR_dataset.py'. The main function is not used at all.
Another functions in 'SR_dataset.py' are used in other files such as 'train.py'

**Comment by Adarsh474532** [comment]
ok

**Comment by Adarsh474532** [comment]
one last question sir 
![image](https://user-images.githubusercontent.com/51045580/127274428-b8255f0c-a74c-4ecb-85b6-5c509653f73c.png)

np.set_printoptions(threshold=np.nan)

this line

**Comment by jymsuper** [comment]
You can remove the line

**Comment by Adarsh474532** [comment]
ok

**Comment by Adarsh474532** [comment]
Thank you sir for helping, project is not complete , my hope is down.

Thank you for helping

**Comment by Adarsh474532** [comment]
sir,  in the ubuntu same problem
result is wrong
![Screenshot from 2021-07-28 14-31-49](https://user-images.githubusercontent.com/51045580/127295399-2fa78b1f-0642-4a8c-91c0-6ee04fa7912b.png)

**Comment by Adarsh474532** [comment]
sir,  it is possible any error in feature extraction then files is create error.

**Comment by jymsuper** [comment]
There should be no errors in feature extraction
