### ISSUE TITLE
configure.py 부분에서 궁금한 점이 있습니다.

### ISSUE THREAD

**Issue by dhkstnrh** [jymsuper/SpeakerRecognition_tutorial#21]
아래 코드의 TRAIN_WAV_DIR 와 DEV_WAV_DIR  부분은 무엇을 의미하고 있는건가요?
# Wave path
TRAIN_WAV_DIR = '/home/admin/Desktop/read_25h_2/train'
DEV_WAV_DIR = '/home/admin/Desktop/read_25h_2/dev'

**Comment by jymsuper** [comment]
안녕하세요. WAV_DIR은 feature extraction (wav -> log mel filterbank)를 변환할때 필요한 주소입니다. 하지만 본 코드에선 이미 log mel filterbank feature가 추출되었다고 가정을 하기에 (feature는https://github.com/jymsuper/SpeakerRecognition_tutorial/tree/master/feat_logfbank_nfilt40 경로에 존재) WAV_ DIR은 사용되지 않습니다

**Comment by dhkstnrh** [comment]
감사합니다!
