### ISSUE TITLE
Extract embedding from the .wav

### ISSUE THREAD

**Issue by Vladimetr** [jymsuper/SpeakerRecognition_tutorial#5]
Hi, @jymsuper!
I want to extract embedding from the .wav sound. Tell me please, how can I do this?

**Comment by jymsuper** [comment]
Hi.
I'm sorry but I didn't upload the code for feature extraction.
I will upload the code soon.
As I explained in the README, I used the library below.
https://github.com/jameslyons/python_speech_features

**Comment by Vladimetr** [comment]
Okey, it would be very usefull. Thank you for your development!
