### ISSUE TITLE
train.py 오류

### ISSUE THREAD

**Issue by wwjddbss126** [jymsuper/SpeakerRecognition_tutorial#7]
![image](https://user-images.githubusercontent.com/49504937/92435113-7f5b2400-f1dc-11ea-950f-e103d9914634.png)

ZeroDivisionError: division by zero 
어떻게 해결해야 할까요?

**Comment by jymsuper** [comment]
혹시 feature를 다운받으셨나요?
feat_logfbank_nfilt40 폴더에 있습니다.

**Comment by wwjddbss126** [comment]
빠른 답변 감사합니다 :)
바로 해결했습니다!
