### ISSUE TITLE
how to calculate EER in this code?

### ISSUE THREAD

**Issue by ASR2020Guru** [jymsuper/SpeakerRecognition_tutorial#9]
Hi @jymsuper ,

Thanks for sharing this excellent codes.

I have go through the identification.py and verification.py files for calculate the perfermanes after the enroll process.
Could you give me some ideas about how to calculate the EER ?

Many thanks

**Comment by jymsuper** [comment]
Hi. Thank you for your interest in my work.
I am sorry, but I do not upload the code about calculating the EER.

(1) To calculate the EER, you need to make a trial file for verification.
You can see the example below.
https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/veri_test.txt

(2) In each line, there are two wav files. 
You have to extract the speaker embedding vector for each file.
Then, compute the cosine similarity between the embedding vectors.

(3) Using the code below (from kaldi toolkit), you can calculate the EER.
cf )scores : cosine similarity, labels : label from the trial file.

https://github.com/kaldi-asr/kaldi/blob/master/egs/sre08/v1/sid/compute_min_dcf.py

**Comment by ASR2020Guru** [comment]
great, thanks for your reply @jymsuper 

It is very helpful👍
